package com.intothevortex.interior;

public enum InteractionResult {
    SUCCESS,
    FAILED_INVALID_CONTROL,
    FAILED_NO_POWER,
    FAILED_LOCKED,
    FAILED_INVALID_PHASE,
    FAILED_PERMISSION,
    FAILED_COOLDOWN,
    FAILED_CRASH_STATE,
    FAILED_INVALID_CONTROL_STATE,
    FAILED_TOO_FAR,
    FAILED_WRONG_DIMENSION
}
