package com.intothevortex.tardis;

public enum FlightFailureType {
    NONE,
    INVALID_TRAVEL_STATE,
    INVALID_DESTINATION,
    DESTINATION_BLOCKED,
    LANDING_SEARCH_FAILED,
    EXTERIOR_PLACEMENT_FAILED,
    DESTINATION_DIMENSION_UNAVAILABLE,
    PERSISTED_STATE_INVALID
}
