package com.intothevortex.tardis;

public enum PreflightReason {
    SUCCESS,
    MISSING_TARDIS_DATA,
    NO_POWER,
    HANDBRAKE_ENGAGED,
    THROTTLE_IDLE,
    ALREADY_DEMATERIALIZING,
    ALREADY_IN_FLIGHT,
    ALREADY_MATERIALIZING,
    NO_DESTINATION,
    INVALID_DESTINATION,
    INVALID_DIMENSION,
    INSUFFICIENT_FUEL,
    CRASHED,
    INVALID_TRAVEL_STATE
}
