package com.intothevortex.tardis;

import java.util.UUID;
import net.minecraft.core.BlockPos;

public record TardisData(UUID id, UUID ownerId, UUID exteriorId, String exterior, String interior, String dimension, BlockPos position, BlockPos interiorDoor, boolean interiorDoorStored, float yaw, boolean locked, boolean doorOpen, boolean powered, boolean refueling, boolean interiorInitialized, String doorAnimation, String dematAnimation, String matAnimation, TardisTravelState travelState, int phaseTicks, int flightTicks, int targetFlightTicks, String travelSourceDimension, BlockPos travelSourcePosition, float travelSourceYaw, String travelDestinationDimension, BlockPos travelDestinationPosition, float travelDestinationYaw, int throttleStage, boolean handbrakeEngaged, double fuel, double maxFuel, double travelFuelCost, boolean fuelCommitted, int dataVersion, FlightCondition flightCondition, FlightFailureType lastFailureType, String lastFailureDetails, String requestedDestinationDimension, BlockPos requestedDestinationPosition, float requestedDestinationYaw, String activeFlightEvent, String activeEventControl, int activeEventRemaining, int activeEventElapsed, int activeEventStep, boolean activeEventConsequenceApplied, String activeEventData, boolean autopilot) {
    public TardisData(UUID id, UUID ownerId, UUID exteriorId, String exterior, String interior, String dimension, BlockPos position, BlockPos interiorDoor, boolean interiorDoorStored, float yaw, boolean locked, boolean doorOpen, boolean powered, boolean refueling, boolean interiorInitialized, String doorAnimation, String dematAnimation, String matAnimation, TardisTravelState travelState, int phaseTicks, int flightTicks, int targetFlightTicks, String travelSourceDimension, BlockPos travelSourcePosition, float travelSourceYaw, String travelDestinationDimension, BlockPos travelDestinationPosition, float travelDestinationYaw) {
        this(id, ownerId, exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, 0, false, TardisFuelManager.DEFAULT_MAX_FUEL, TardisFuelManager.DEFAULT_MAX_FUEL, 0.0D, false, 1, FlightCondition.NORMAL, FlightFailureType.NONE, "", travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, "", "", 0, 0, 0, false, "", false);
    }

    public TardisData sanitized() {
        TardisTravelState state = travelState == null ? TardisTravelState.LANDED : travelState;
        FlightCondition condition = flightCondition == null ? FlightCondition.NORMAL : flightCondition;
        FlightFailureType failure = lastFailureType == null ? FlightFailureType.NONE : lastFailureType;
        int stage = Math.clamp(throttleStage, 0, 4);
        boolean missingCapacity = !Double.isFinite(maxFuel) || maxFuel <= 0.0D;
        double capacity = missingCapacity ? TardisFuelManager.DEFAULT_MAX_FUEL : maxFuel;
        double amount = Double.isFinite(fuel) ? Math.clamp(fuel, 0.0D, capacity) : capacity;
        if (missingCapacity && fuel == 0.0D) amount = capacity;
        double cost = state == TardisTravelState.LANDED || !Double.isFinite(travelFuelCost) || travelFuelCost < 0.0D ? 0.0D : travelFuelCost;
        boolean committed = state != TardisTravelState.LANDED && fuelCommitted;
        BlockPos requestedPosition = requestedDestinationPosition == null ? travelDestinationPosition : requestedDestinationPosition;
        String requestedDimension = requestedDestinationDimension == null ? travelDestinationDimension : requestedDestinationDimension;
        float requestedYaw = requestedDestinationDimension == null ? travelDestinationYaw : requestedDestinationYaw;
        return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, state, Math.max(0, phaseTicks), Math.max(0, flightTicks), Math.max(0, targetFlightTicks), travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, stage, handbrakeEngaged, amount, capacity, cost, committed, Math.max(1, dataVersion), condition, failure, lastFailureDetails, requestedDimension, requestedPosition, requestedYaw, activeFlightEvent, activeEventControl, Math.max(0, activeEventRemaining), Math.max(0, activeEventElapsed), Math.max(0, activeEventStep), activeEventConsequenceApplied, activeEventData, autopilot);
    }

    public boolean isHandbrakeEngaged() { return handbrakeEngaged; }
    public int getThrottleStage() { return throttleStage; }
    public boolean isCrashed() { return flightCondition == FlightCondition.CRASHED; }
    public boolean canUseNormalFlightControls() { return TardisCrashManager.canUseNormalFlightControls(this); }
    public TardisData withAutopilot(boolean value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted, dataVersion, flightCondition, lastFailureType, lastFailureDetails, requestedDestinationDimension, requestedDestinationPosition, requestedDestinationYaw, activeFlightEvent, activeEventControl, activeEventRemaining, activeEventElapsed, activeEventStep, activeEventConsequenceApplied, activeEventData, value); }
    public TardisData withFlightCondition(FlightCondition value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted, dataVersion, value, lastFailureType, lastFailureDetails, requestedDestinationDimension, requestedDestinationPosition, requestedDestinationYaw, activeFlightEvent, activeEventControl, activeEventRemaining, activeEventElapsed, activeEventStep, activeEventConsequenceApplied, activeEventData); }
    public TardisData withFailure(FlightFailureType type, String details) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted, dataVersion, flightCondition, type, details, requestedDestinationDimension, requestedDestinationPosition, requestedDestinationYaw, activeFlightEvent, activeEventControl, activeEventRemaining, activeEventElapsed, activeEventStep, activeEventConsequenceApplied, activeEventData); }
    public TardisData withRequestedDestination(TardisTravelDestination value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted, dataVersion, flightCondition, lastFailureType, lastFailureDetails, value.dimension(), value.position(), value.yaw(), activeFlightEvent, activeEventControl, activeEventRemaining, activeEventElapsed, activeEventStep, activeEventConsequenceApplied, activeEventData); }
    public TardisData withFlightEvent(String id, String control, int remaining, int elapsed, int step, boolean consequenceApplied, String eventData) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted, dataVersion, flightCondition, lastFailureType, lastFailureDetails, requestedDestinationDimension, requestedDestinationPosition, requestedDestinationYaw, id, control, remaining, elapsed, step, consequenceApplied, eventData); }
    public TardisData clearFlightEvent() { return withFlightEvent("", "", 0, 0, 0, false, ""); }
    public float fuelFraction() { return maxFuel <= 0.0D ? 0.0F : (float) (fuel / maxFuel); }
    public TardisData withExterior(UUID value) { return copy(value, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withExteriorType(String value) { return copy(exteriorId, value, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withDoorOpen(boolean value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, value, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withLocked(boolean value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, value, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withPowered(boolean value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, value, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withRefueling(boolean value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, value, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withInteriorInitialized(boolean value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, value, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withInterior(String value) { return copy(exteriorId, exterior, value, dimension, position, new BlockPos(0, 64, 0), false, yaw, locked, doorOpen, powered, refueling, false, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withInteriorDoor(BlockPos value) { return copy(exteriorId, exterior, interior, dimension, position, value, true, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withTravel(TardisTravelState state, int phase, int flight, int target, TardisTravelDestination source, TardisTravelDestination destination) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, state, phase, flight, target, source.dimension(), source.position(), source.yaw(), destination.dimension(), destination.position(), destination.yaw(), throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withFlightControls(int throttle, boolean handbrake) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, Math.clamp(throttle, 0, 4), handbrake, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withFuel(double value) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, Math.clamp(value, 0.0D, maxFuel), maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withMaxFuel(double value) { double capacity = Double.isFinite(value) && value > 0.0D ? value : TardisFuelManager.DEFAULT_MAX_FUEL; return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, Math.clamp(fuel, 0.0D, capacity), capacity, travelFuelCost, fuelCommitted); }
    public TardisData withTravelFuel(double cost, boolean committed) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, cost, committed); }
    public TardisData withAnimations(String door, String demat, String mat) { return copy(exteriorId, exterior, interior, dimension, position, interiorDoor, interiorDoorStored, yaw, locked, doorOpen, powered, refueling, interiorInitialized, door, demat, mat, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    public TardisData withLanded(TardisTravelDestination destination) { return copy(exteriorId, exterior, interior, destination.dimension(), destination.position(), interiorDoor, interiorDoorStored, destination.yaw(), locked, false, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, TardisTravelState.LANDED, 0, 0, 0, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, 0.0D, false); }
    public TardisData withExteriorLocation(TardisTravelDestination destination) { return copy(exteriorId, exterior, interior, destination.dimension(), destination.position(), interiorDoor, interiorDoorStored, destination.yaw(), locked, doorOpen, powered, refueling, interiorInitialized, doorAnimation, dematAnimation, matAnimation, travelState, phaseTicks, flightTicks, targetFlightTicks, travelSourceDimension, travelSourcePosition, travelSourceYaw, travelDestinationDimension, travelDestinationPosition, travelDestinationYaw, throttleStage, handbrakeEngaged, fuel, maxFuel, travelFuelCost, fuelCommitted); }
    private TardisData copy(UUID exteriorEntityId, String exteriorType, String interiorType, String exteriorDimension, BlockPos exteriorPosition, BlockPos door, boolean doorStored, float exteriorYaw, boolean isLocked, boolean isDoorOpen, boolean isPowered, boolean isRefueling, boolean initialized, String doorId, String dematId, String matId, TardisTravelState state, int phase, int flight, int target, String sourceDimension, BlockPos sourcePosition, float sourceYaw, String destinationDimension, BlockPos destinationPosition, float destinationYaw, int throttle, boolean handbrake, double currentFuel, double maximumFuel, double fuelCost, boolean committed) { return copy(exteriorId, exteriorType, interiorType, exteriorDimension, exteriorPosition, door, doorStored, exteriorYaw, isLocked, isDoorOpen, isPowered, isRefueling, initialized, doorId, dematId, matId, state, phase, flight, target, sourceDimension, sourcePosition, sourceYaw, destinationDimension, destinationPosition, destinationYaw, throttle, handbrake, currentFuel, maximumFuel, fuelCost, committed, dataVersion, flightCondition, lastFailureType, lastFailureDetails, requestedDestinationDimension, requestedDestinationPosition, requestedDestinationYaw, activeFlightEvent, activeEventControl, activeEventRemaining, activeEventElapsed, activeEventStep, activeEventConsequenceApplied, activeEventData, autopilot); }
    private TardisData copy(UUID exteriorEntityId, String exteriorType, String interiorType, String exteriorDimension, BlockPos exteriorPosition, BlockPos door, boolean doorStored, float exteriorYaw, boolean isLocked, boolean isDoorOpen, boolean isPowered, boolean isRefueling, boolean initialized, String doorId, String dematId, String matId, TardisTravelState state, int phase, int flight, int target, String sourceDimension, BlockPos sourcePosition, float sourceYaw, String destinationDimension, BlockPos destinationPosition, float destinationYaw, int throttle, boolean handbrake, double currentFuel, double maximumFuel, double fuelCost, boolean committed, int version, FlightCondition condition, FlightFailureType failure, String details, String requestedDimension, BlockPos requestedPosition, float requestedYaw, String eventId, String eventControl, int eventRemaining, int eventElapsed, int eventStep, boolean eventConsequenceApplied, String eventData) { return copy(exteriorEntityId, exteriorType, interiorType, exteriorDimension, exteriorPosition, door, doorStored, exteriorYaw, isLocked, isDoorOpen, isPowered, isRefueling, initialized, doorId, dematId, matId, state, phase, flight, target, sourceDimension, sourcePosition, sourceYaw, destinationDimension, destinationPosition, destinationYaw, throttle, handbrake, currentFuel, maximumFuel, fuelCost, committed, version, condition, failure, details, requestedDimension, requestedPosition, requestedYaw, eventId, eventControl, eventRemaining, eventElapsed, eventStep, eventConsequenceApplied, eventData, autopilot); }
    private TardisData copy(UUID exteriorEntityId, String exteriorType, String interiorType, String exteriorDimension, BlockPos exteriorPosition, BlockPos door, boolean doorStored, float exteriorYaw, boolean isLocked, boolean isDoorOpen, boolean isPowered, boolean isRefueling, boolean initialized, String doorId, String dematId, String matId, TardisTravelState state, int phase, int flight, int target, String sourceDimension, BlockPos sourcePosition, float sourceYaw, String destinationDimension, BlockPos destinationPosition, float destinationYaw, int throttle, boolean handbrake, double currentFuel, double maximumFuel, double fuelCost, boolean committed, int version, FlightCondition condition, FlightFailureType failure, String details, String requestedDimension, BlockPos requestedPosition, float requestedYaw, String eventId, String eventControl, int eventRemaining, int eventElapsed, int eventStep, boolean eventConsequenceApplied, String eventData, boolean pilot) { return new TardisData(id, ownerId, exteriorEntityId, exteriorType, interiorType, exteriorDimension, exteriorPosition, door, doorStored, exteriorYaw, isLocked, isDoorOpen, isPowered, isRefueling, initialized, doorId, dematId, matId, state, phase, flight, target, sourceDimension, sourcePosition, sourceYaw, destinationDimension, destinationPosition, destinationYaw, throttle, handbrake, currentFuel, maximumFuel, fuelCost, committed, version, condition, failure, details, requestedDimension, requestedPosition, requestedYaw, eventId, eventControl, eventRemaining, eventElapsed, eventStep, eventConsequenceApplied, eventData, pilot); }
}
